roboclaw_driver:
  ros__parameters:
    # RoboClaw 1 (On: W1=M2 sag, W2=M1 sol)
    port_front: "/dev/roboclaw_front"
    baud_front: 38400
    address_front: 0x80

    # RoboClaw 2 (Arka: W3=M2)
    port_rear: "/dev/roboclaw_rear"
    baud_rear: 38400
    address_rear: 0x81

    loop_rate_hz: 50.0
    encoder_ticks_per_rev: 750
